../../../rdl/outputs/registers_pkg.sv
../../../rdl/outputs/registers.sv
../../../axi4_lite/axi4_lite_pkg.sv
../../../axi4_lite/axi4_lite_if.sv
../../../axi4_lite/unit_test_pkg.sv
../../../rtl/modul_studenta.sv
../../../rtl/Uart_module.sv
../../../rtl/clock_div.sv
../../../rtl/BCH_encoder.sv
../../../rtl/BCH_determinant.sv
../../../rtl/BCH_minor.sv
../../../rtl/BCH_error_place.sv
../../../rtl/BCH_decoder.sv
../../../quartus/mnozenie.v
../../../quartus/mnozenie/mnozenie_0002.v
/tools/intel/quartus/standard/22.1/quartus/eda/sim_lib/altera_lnsim.sv
../../../rtl/Gauss/gng.v
../../../rtl/Gauss/gng_ctg.v
../../../rtl/Gauss/gng_coef.v
../../../rtl/Gauss/gng_interp.v
../../../rtl/Gauss/gng_lzd.v
../../../rtl/Gauss/gng_smul_16_18_sadd_37.v
../../../rtl/Gauss/gng_smul_16_18.v
