../../../rdl/outputs/registers_pkg.sv
../../../rdl/outputs/registers.sv
../../../axi4_lite/axi4_lite_pkg.sv
../../../axi4_lite/axi4_lite_if.sv
../../../axi4_lite/unit_test_pkg.sv
../../../rtl/modul_studenta.sv
../../../rtl/Gauss/gng.v
../../../rtl/Gauss/gng_ctg.v
../../../rtl/Gauss/gng_coef.v
../../../rtl/Gauss/gng_interp.v
../../../rtl/Gauss/gng_lzd.v
../../../rtl/Gauss/gng_smul_16_18_sadd_37.v
../../../rtl/Gauss/gng_smul_16_18.v
