// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package registers_pkg;

    localparam REGISTERS_DATA_WIDTH = 32;
    localparam REGISTERS_MIN_ADDR_WIDTH = 3;

    typedef struct {
        logic [7:0] value;
    } registers__LEDS__LED__out_t;

    typedef struct {
        registers__LEDS__LED__out_t LED;
    } registers__LEDS__out_t;

    typedef struct {
        registers__LEDS__out_t LEDS;
    } registers__out_t;
endpackage